services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${db_user}
            WORDPRESS_DB_PASSWORD: ${db_pass}
            WORDPRESS_DB_NAME: ${db_name}
        volumes:
            - wordpress:/var/www/html

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${db_name}
            MYSQL_USER: ${db_user}
            MYSQL_PASSWORD: ${db_pass}
            MYSQL_RANDOM_ROOT_PASSWORD: ${rand_pass_root}
        volumes:
            - db:/var/lib/mysql

volumes:
    wordpress:
    db:
